[package]
name = "barcode"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
exclude_entrypoint = []
test-bpf = []

[dependencies]
borsh = "0.9.3"
borsh-derive = "0.9.1"
solana-program = "1.14.7"

[dev-dependencies]
solana-program-test = "1.14.7"
solana-sdk = "1.14.7"
