[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_program_barcode = "CjzUfJHocMEMTycycyPMtDVuttjTtaZMjtnDqTj3MXsN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/konstantintuev/.config/solana/id.json"

[scripts]
test_create = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'create_entry' tests/**/*.ts"
test_get = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'get_entries' tests/**/*.ts"
